### ISSUE TITLE
Make the home page mobile friendly

### ISSUE THREAD

**Issue by d4rkpassenger** [angular-selfstudy-group/show-tarto#20]
- Touch capable devices don't have hover state, but currently we have hover state defined for movie cards.
On real mobile device it cause flickering during scrolling when the user scrolls while he is touching one of the movie cards.
- target: look nice on iphone 5s

**Comment by spacedaniel22** [comment]
![img_0241](https://user-images.githubusercontent.com/7096543/28464072-ef47ae5e-6e23-11e7-9864-c4b1f3c6ecb9.png)
![img_0239](https://user-images.githubusercontent.com/7096543/28464073-ef4bf3ce-6e23-11e7-8d21-49986ae787a3.png)
![img_0240](https://user-images.githubusercontent.com/7096543/28464074-ef522ab4-6e23-11e7-8b6f-1117702bb41a.png)

**Comment by ityu** [comment]
Sidebar Issue fixed on #ST20-home-page-mobile-friendly branch.

I changed the Sidenav mode from "side" to "over"
[Sidenav doc](https://github.com/angular/material2/blob/master/src/lib/sidenav/sidenav.md)

**Comment by ityu** [comment]
In the first step fixed the scrolling and card rendering on the Startpage dekstop and mobile platform too.
We should be investigate the CSS Filters and other effects, which property broke the scroll effects.

[Demo page](https://show-tarto.firebaseapp.com/#/home) - based on ST20-home-page-mobile-friendly branch

I guess, we can close the ticket now, because the layout fixed, and start design issue the next milestone.

What do you think?

**Comment by d4rkpassenger** [comment]
Agreed, please proceed with the other issues. I will create a ticket for the design issue.
Please merge the changes into master.
Thanks!
